<?php 
    $context = \Ptf\App\Context::getInstance();
?>
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
    <style type="text/css">
        body {
            background-color: #EEE;
            color: #000;
            font-family: Arial, Verdana, Helvetica, sans-serif;
            font-size: 13px;
        }

        h1 {
            padding: 0;
            font-size: 18px;
        }

        .error {
            background-color: #FFF;
            width: 600px;
            height: 120px;
            margin: 100px auto auto;
            padding: 10px;
            border: 2px solid #AAA;
            border-radius: 15px;
        }

        .icon {
            background: url(<?php echo $context->getBaseUrl(); ?>/ptf/images/icons/warning.png) no-repeat left top;
            width: 96px;
            height: 96px;
            margin-right: 5px;
            float: left;
        }
    </style>
</head>

<body>
    <div class="error">
        <div class="icon"></div>
        <div class="text">
            <h1>Error 404</h1>
            <p>The requested URL <?php echo $context->getRequest()->getRequestUri(); ?> was not found on this server.</p>
        </div>
    </div>
</body>
</html>
